Repository NavAbility/NavAbilitySDK.jl, pull requests merged in 2022-09, with the labels that each got.

#157 better standardize getData and Entry
  .github/workflows/tests.yml
  src/Deprecated.jl
  src/NavAbilitySDK.jl
  src/navability/services/DataBlobs.jl
Labels: standardization

#158 add deleteFactor
  src/NavAbilitySDK.jl
  src/navability/graphql/Factor.jl
  src/navability/services/Factor.jl
  test/integration/runtests.jl
Labels: enhancement

#159 getData better aligned with UUID
  src/Deprecated.jl
  src/navability/services/DataBlobs.jl
Labels: refactor

#161 test deleteFactor
  test/integration/testFactor.jl
Labels: test
