Repository NavAbility/NavAbilitySDK.jl, pull requests merged in 2023-02, with the labels that each got.

#191 Release 0.4.10
  Project.toml
  src/Deprecated.jl
  src/NavAbilitySDK.jl
  src/navability/entities/NavAbilityClient.jl
  src/navability/graphql/DataBlobs.jl
  src/navability/graphql/Variable.jl
  src/navability/services/DataBlobs.jl
  src/navability/services/Variable.jl
  test/integration/testVariable.jl
  test/load/blobload.jl
Labels: release

#197 docs wip get graph
  docs/make.jl
  docs/src/buildgraph.md
  docs/src/factors.md
  docs/src/start.md
  docs/src/variables.md
Labels: documentation

#198 docs factors page
  docs/src/factors.md
Labels: documentation

#199 docs build and solve graph pages
  docs/make.jl
  docs/src/buildgraph.md
  docs/src/factors.md
  docs/src/solvers.md
Labels: documentation

#200 use instead listBlobs getBlob
  src/navability/services/DataBlobs.jl
Labels: enhancement, standardization, deprecation

#202 fix test DFG_VERSION bug
  src/NavAbilitySDK.jl
  src/navability/entities/Factor.jl
  src/navability/entities/Variable.jl
  test/unit/testVariables.jl
Labels: bug fix, test

#201 fix export blobs, expand docs on refs and blobs
  docs/make.jl
  docs/src/factors.md
  docs/src/summary.md
  docs/src/variables.md
  src/NavAbilitySDK.jl
  src/navability/entities/Client.jl
  src/navability/entities/Factor.jl
  src/navability/entities/InferenceTypes.jl
  src/navability/entities/NavAbilityClient.jl
  src/navability/services/Factor.jl
  src/navability/services/Variable.jl
Labels: documentation

#203 more auto docs
  docs/src/buildgraph.md
  docs/src/solvers.md
  src/navability/services/Utils.jl
Labels: documentation

#194 First pass on fixing adding blob entry
  src/navability/graphql/DataBlobs.jl
  src/navability/services/DataBlobs.jl
  src/navability/services/Variable.jl
Labels: bug fix

#204 updates and fixes (breaking changes)
  README.md
  docs/src/start.md
  src/Deprecated.jl
  src/navability/entities/Variable.jl
  src/navability/graphql/Factor.jl
  src/navability/graphql/Session.jl
  src/navability/graphql/Status.jl
  src/navability/services/DataBlobs.jl
  src/navability/services/Variable.jl
Labels: enhancement, standardization, deprecation, data: BlobEntry=>Blob

#205 bump v0.5
  Project.toml
Labels: enhancement

#206 getBlob as Vec{UInt8} not IO
  src/navability/services/DataBlobs.jl
Labels: enhancement, breaking change

#207 v0.5.0-rc1
  src/navability/services/DataBlobs.jl
Labels: release

#209 missed api depr addBlob
  Project.toml
  src/Deprecated.jl
  src/NavAbilitySDK.jl
  src/navability/services/DataBlobs.jl
Labels: standardization, deprecation
