Repository NavAbility/NavAbilitySDK.jl, pull requests merged in 2024-10, with the labels that each got.

#259 Update to the Org-Fg structure
  Project.toml
  attic/navability/entities/UserRobotSession.jl
  attic/navability/graphql/UserRobotSession.jl
  attic/navability/services/UserRobotSession.jl
  sandbox/AlternateAPICalls.jl
  sandbox/sandbox.jl
  src/Deprecated.jl
  src/NavAbilityClient.jl
  src/NavAbilityDFG.jl
  src/NavAbilityModel.jl
  src/NavAbilitySDK.jl
  src/entities/Factor.jl
  src/entities/InferenceTypes.jl
  src/entities/Map.jl
  src/entities/NvaNodes.jl
  src/entities/Variable.jl
  src/graphql/BlobEntry.jl
  src/graphql/BlobStore.jl
  src/graphql/Factor.jl
  src/graphql/Map.jl
  src/graphql/Model.jl
  src/graphql/Variable/PPE.jl
  src/graphql/Variable/SolverData.jl
  src/graphql/Variable/Variable.jl
  src/services/Agent.jl
  src/services/BlobEntry.jl
  src/services/BlobStore.jl
  src/services/Common.jl
  src/services/Factor.jl
  src/services/FactorGraph.jl
  src/services/Map.jl
  src/services/Model.jl
  src/services/Org.jl
  src/services/PPE.jl
  src/services/SolverData.jl
  src/services/StandardAPI.jl
  src/services/Variable.jl
  src/services/Workers.jl
  test/integration/InterfaceTests.jl
  test/integration/runtests.jl
  test/integration/testStandardAPI.jl
Labels: needs testing, refactor, breaking change

#260 standardize to dfg v0.25 `Graph` and cleanup
  src/NavAbilityDFG.jl
  src/NavAbilitySDK.jl
  src/graphql/BlobEntry.jl
  src/services/AsyncCalls.jl
  src/services/BlobEntry.jl
  src/services/FactorGraph.jl
  src/services/Model.jl
  test/integration/testStandardAPI.jl
Labels: standardization, maintenance

#262 extend getAgentBlobEntries
  src/entities/Variable.jl
  src/services/BlobEntry.jl
Labels: enhancement, data: BlobEntry=>Blob, agent

#263 Use the dedicated listVariables endpoint and start using executeGql wrapper
  src/graphql/Variable/Variable.jl
  src/services/Agent.jl
  src/services/BlobEntry.jl
  src/services/Common.jl
  src/services/Variable.jl
Labels: enhancement, standardization

#264 multipart blob upload
  src/graphql/BlobStore.jl
  src/services/BlobStore.jl
Labels: enhancement, data: BlobEntry=>Blob

#266 Add addFactors and better listFactors
  src/NavAbilitySDK.jl
  src/graphql/Factor.jl
  src/services/Common.jl
  src/services/Factor.jl
  src/services/Variable.jl
Labels: enhancement, standardization, factors, performance

#267 Update Model and Patch docs for v0.8
  docs/make.jl
  docs/src/index.md
  docs/src/summary.md
  docs/todo/buildgraph.md
  docs/todo/factors.md
  docs/todo/index_extra.md
  docs/todo/solvers.md
  docs/todo/start.md
  docs/todo/variables.md
  src/NavAbilityClient.jl
  src/NavAbilityDFG.jl
  src/entities/NvaNodes.jl
  src/entities/Variable.jl
  src/graphql/Model.jl
  src/services/BlobEntry.jl
  src/services/Common.jl
  src/services/FactorGraph.jl
  src/services/Model.jl
  src/services/Variable.jl
Labels: documentation, maintenance
